name: Node.js Package
on:
  push:
    branches: [ temp ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: |
        npm install
        npm run build-prod
    - run: npm publish dist/ngx-store/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
